import type { MenuItem } from "@/types/menu";
import type { Transaction } from "@/types/transaction";
import {
  Home,
  TrendingUp,
  PieChart,
  ArrowLeftRight,
  FileText,
  CreditCard,
  FileBarChart,
  Users,
} from "lucide-react";

export const menuItems: MenuItem[] = [
  { title: "Home", url: "#", icon: Home },
  { title: "Cash Flow", url: "#", icon: TrendingUp },
  { title: "Budget", url: "#", icon: PieChart },
  { title: "Transaction", url: "#", icon: ArrowLeftRight },
  { title: "Invoice", url: "#", icon: FileText },
  { title: "Bill Pay", url: "#", icon: CreditCard },
  {
    title: "Tax Report",
    url: "#",
    icon: FileBarChart,
    hasDropdown: true,
    subItems: [
      { title: "VAT", url: "#" },
      { title: "Withholding", url: "#" },
    ],
  },
  { title: "Card", url: "#", icon: CreditCard },
  { title: "Team", url: "#", icon: Users },
];
export const mockTransactions: Transaction[] = [
  {
    id: "1",
    status: "pending",
    date: "01/01/2024",
    member: "Ahmed Abbas",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
  {
    id: "2",
    status: "pending",
    date: "01/01/2025",
    member: "Hamza Zamzami",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
  {
    id: "3",
    status: "approved",
    date: "03/05/2025",
    member: "Turki Mutairi",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
  {
    id: "4",
    status: "approved",
    date: "06/06/2025",
    member: "Meshal Khayat",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
  {
    id: "5",
    status: "approved",
    date: "07/07/2025",
    member: "Ibrahim Alghamdi",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
  {
    id: "6",
    status: "approved",
    date: "01/01/2026",
    member: "Ahmed Alzahrani",
    budget: "Marketing",
    type: "Manual",
    vendor: "Amazon Web",
    invoiceNumber: "SA-252343",
    amount: 10000,
  },
];
